### ISSUE TITLE
cbench example not work

### ISSUE THREAD

**Issue by mikenekonotano** [shun159/flexx#3]
Environments:  
--------------------------------------
OS: MacOSX 10.10.1 
CPU: Core i5 2.7Ghz x 4Core
Memory: 32GB

Erlang/OTP 17 [erts-6.3] [source-f9282c6] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

./start.sh 
--------------------------------------
Erlang/OTP 17 [erts-6.3] [source-f9282c6] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

=PROGRESS REPORT==== 10-Feb-2015::03:51:13 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.35.0>},
                       {name,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 10-Feb-2015::03:51:13 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.36.0>},
                       {name,overload},
                       {mfargs,{overload,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 10-Feb-2015::03:51:13 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.34.0>},
                       {name,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 10-Feb-2015::03:51:13 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.37.0>},
                       {name,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 10-Feb-2015::03:51:13 ===
         application: sasl
          started_at: nonode@nohost
{"init terminating in do_boot",{undef,[{cbench,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
--------------------------------------

**Comment by shun159** [comment]
すみません、ありがとうございます！
ちょっとみてみます

**Comment by shun159** [comment]
すみませんが、ちなみにrakeは走りましたか？

**Comment by shun159** [comment]
98f9fe7 これで動くはずです。済みませんが、試していただいてよろしいですか？

**Comment by shun159** [comment]
@mikenekonotano
治っているはずなので、クローズしまーす。
また再発したら再オープンしてくださーい。

**Comment by shun159** [comment]
@mikenekonotano 
すみませんが、　ビルドのログをここに貼り付けてもらえますでしょうか？？

**Comment by shun159** [comment]
@mikenekonotano ping!

すみませんが、MacOSX では動作未確認、というか
手元にMacが無いので、残念ながら今のところそちらまでカバーできないです。

現在は、CentOS6 もしくは、Ubuntuでの動作とビルドについては確認しています。
